logo: /assets/img/logo.png
show_downloads: true
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0

# Customization
title: "BC3995 Project"
description: "Progress report of building a website for a small business owner."

